image:
    - Visual Studio 2015
    - Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\llvm
shallow_clone: true

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    BUILD_PROJECT: clang
    BUILD_MASTER: true
    LLVM_VERSION: x.x.x

    # 3.4.2 ............ builds on msvc10 and up (clang-3.4.2 doesn't build on msvc14 and up)
    # 3.5.2 ............ skip (a very troublesome release)
    # 3.6.0 to 3.9.1 ... build on msvc12 and up
    # 4.0.1 to 7.1.0 ... build on msvc14 and up
    # 8.0.0 ............ builds on msvc15 and up

    matrix:
#        -   TOOLCHAIN: msvc10
#            CRT: msvcrt
#
#        -   TOOLCHAIN: msvc10
#            CRT: libcmt
#
#        -   TOOLCHAIN: msvc12
#            CRT: msvcrt
#
#        -   TOOLCHAIN: msvc12
#            CRT: libcmt
#
#        -   TOOLCHAIN: msvc14
#            CRT: msvcrt
#
#        -   TOOLCHAIN: msvc14
#            CRT: libcmt

        -   TOOLCHAIN: msvc15
            CRT: msvcrt

        -   TOOLCHAIN: msvc15
            CRT: libcmt

matrix:
    fast_finish: false

    exclude:
        -   image: Visual Studio 2015
            TOOLCHAIN: msvc15

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc10

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc12

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc14


install:
    - call set-env.bat %CONFIGURATION% %PLATFORM% %TOOLCHAIN% %CRT%
    - call install.bat

build_script:
    - call build.bat

artifacts:
    -   path: $(DEPLOY_FILE)
        name: deploy_file

deploy:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: jpZmZjs4rexF7ix1wvN56hvAac2tGVAffQGsygfqMfR34Ls1SkvC1DQaf4On7RTB

    artifact: deploy_file
    force_update: true

    on:
        appveyor_repo_tag: true
