image: Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\llvm
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        -   TOOLCHAIN: msvc14
            CRT: libcmt

        -   TOOLCHAIN: msvc14
            CRT: msvcrt

install:
    - call set-env.bat %PLATFORM% %TOOLCHAIN% %CRT%
    - call install.bat

build_script:
    - set THIS_DIR=%CD%

    - mkdir llvm\build
    - cd llvm\build
    - cmake .. %CMAKE_FLAGS%
    - cmake --build . -- %MSBUILD_FLAGS%
    - cmake --build . --target install

    - cd %THIS_DIR%

    - 7z a -t7z %LLVM_RELEASE_FILE% %LLVM_RELEASE_NAME%

artifacts:
    -   path: $(LLVM_RELEASE_FILE)
        name: llvm_package

deploy:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: tJE3cSm72rg6tNs4ESK38HU9IAhN7Eh/3kvQZhQKuUelpHT55L/MiPOhOcCdw26u

    artifact: llvm_package
    force_update: true

    on:
        appveyor_repo_tag: true
